version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DevConnection=Host=dpg-crp9fmo8fa8c73ducsb0-a.oregon-postgres.render.com;Database=todolistdb_dg7h;Username=admin;Password=txXNRl6KFWQAOM5YROw1V56QWjhZg3L9;
      - Jwt__Key=2nmqkYbtQQrGPj3IsCt1IkMiiWp4HYcSrzTGaUCeKT0=
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: todolistdb_dg7h
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: txXNRl6KFWQAOM5YROw1V56QWjhZg3L9
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
