version: '3.8'

services:
  webapi:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DevConnection=Server=db;Database=TodoListDB;User=sa;Password=Actionscheduler@123;TrustServerCertificate=True;MultipleActiveResultSets=True;
      - Jwt__Key=2nmqkYbtQQrGPj3IsCt1IkMiiWp4HYcSrzTGaUCeKT0=
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Actionscheduler@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
